// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF_dhn69I3r74203tpXK-WxWup0lGInAs',
    appId: '1:1038294326845:web:156236d7d4ff49fbba5454',
    messagingSenderId: '1038294326845',
    projectId: 'catch-a-phish',
    authDomain: 'catch-a-phish.firebaseapp.com',
    storageBucket: 'catch-a-phish.firebasestorage.app',
    measurementId: 'G-97BN47Y216',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVeMr3PqFlKM0aihhESP7FcfTawmHD3zM',
    appId: '1:1038294326845:android:6c9eeee074ad848cba5454',
    messagingSenderId: '1038294326845',
    projectId: 'catch-a-phish',
    storageBucket: 'catch-a-phish.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvbwywhRmVec0arG3qeAzyHsVqcAhtDio',
    appId: '1:1038294326845:ios:2e2125d1f771ba4cba5454',
    messagingSenderId: '1038294326845',
    projectId: 'catch-a-phish',
    storageBucket: 'catch-a-phish.firebasestorage.app',
    iosBundleId: 'com.example.catchAPhish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvbwywhRmVec0arG3qeAzyHsVqcAhtDio',
    appId: '1:1038294326845:ios:2e2125d1f771ba4cba5454',
    messagingSenderId: '1038294326845',
    projectId: 'catch-a-phish',
    storageBucket: 'catch-a-phish.firebasestorage.app',
    iosBundleId: 'com.example.catchAPhish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF_dhn69I3r74203tpXK-WxWup0lGInAs',
    appId: '1:1038294326845:web:d26350b35ef8c1d8ba5454',
    messagingSenderId: '1038294326845',
    projectId: 'catch-a-phish',
    authDomain: 'catch-a-phish.firebaseapp.com',
    storageBucket: 'catch-a-phish.firebasestorage.app',
    measurementId: 'G-G8SW6CV8EK',
  );
}
